context:
  name: libpinch
  version: "1.3.0"
  author: "mhekkel"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 67f6893894c020dfdc242a6ca38e8c6384fc518fdbbfcf248a5aea6ce485d39c
  patches:
    # Refer to https://github.com/mhekkel/libpinch/pull/1
    - fix-include-target_sources.patch
    # Remove the header include since cryptopp/factory.h is not included in conda-forge's cryptopp
    # Upstream code includes the header but does not use it
    - remove-include-factory-header.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "make" if unix }}
    - ${{ "jom" if win }}
    - cmake
    - pkg-config
  host:
    - asio
    - cryptopp
    - zlib
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x.x") }}

tests:
  - package_contents:
      include:
        - pinch.hpp
        - pinch/asio.hpp
      lib:
        - pinch

about:
  homepage: https://github.com/mhekkel/libpinch
  repository: https://github.com/mhekkel/libpinch
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: "Library for asynchronous SSH"
  description: |
    This library provides asynchronous SSH for use in client applications.

extra:
  recipe-maintainers:
    - eunos-1128
