context:
  name: libpinch
  version: "1.4.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: d532602c0dd496716f3e23827e64b8fbbea31a54772ec1e1b25fd494d275deda
  patches:
    # Remove the header include since cryptopp/factory.h is not included in conda-forge's cryptopp
    # Upstream code includes the header but does not use it
    - remove-include-factory-header.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "make" if unix }}
    - ${{ "jom" if win }}
    - cmake
    - pkg-config
  host:
    - asio
    - cryptopp
    - libmcfp
    - zlib
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x.x") }}

tests:
  - package_contents:
      include:
        - pinch.hpp
        - pinch/asio.hpp
      lib:
        - pinch

about:
  homepage: https://forge.hekkelman.net/maarten/libpinch
  repository: https://forge.hekkelman.net/maarten/libpinch
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: "Library for asynchronous SSH"
  description: |
    This library provides asynchronous SSH for use in client applications.

extra:
  recipe-maintainers:
    - eunos-1128
